spring.config.import=optional:file:.env[.properties]
spring.application.name=minurl

app.base-url=${APP_BASE_URL}
app.default-expiry-in-days=${PP_DEFAULT_EXPIRY_IN_DAYS:30}
app.validate-original-url=${APP_VALIDATE_ORIGINAL_URL}

spring.datasource.url=jdbc:postgresql://${DATABASE_HOST}/${DATABASE_NAME}?sslmode=${DATABASE_SSLMODE}&channelBinding=${DATABASE_CHANNEL_BINDING}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.open-in-view=false

