spring.config.import=optional:file:.env[.properties]
spring.application.name=minurl

app.base-url=http://localhost:8080
app.default-expiry-in-days=30
app.validate-original-url=true

spring.datasource.url=jdbc:postgresql://${DATABASE_HOST}/${DATABASE_NAME}?sslmode=${DATABASE_SSLMODE}&channelBinding=${DATABASE_CHANNEL_BINDING}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.open-in-view=false
#spring.data.hibernate.ddl-auto=update